enigma2 20121210 master -> 20121219 ----------------------------------- * HbbTV   - fixed wrong video size in some cases (ARD .e.g) * UPnPMediaRenderer/Demo   - added some more meta-types (flac, avi, divx, wav)   - fixed Demo Renderer crashing when there is certain metadata missing - fixed broken servicelist filtering by satellite position - fixed possible error messages like "AttributeError: class ServiceEventTracker has no attribute 'oldRef'" - fixed not stored scpcSearchRange and toneAmplitude settings in settings file - get rid of "No fast winding possible yet.. but you can use the number buttons to skip forward/backward!" message   when zap from one iptv/radio service to another one